import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next"
import "./globals.css";
import { Gabarito } from 'next/font/google'
import { Arimo } from 'next/font/google'

const inter = Inter({ 
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-inter', });
const gabarito = Gabarito({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-gabarito',
})
const arimo = Arimo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-arimo',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gabarito.variable + ' ' + arimo.variable}>{children}
      <SpeedInsights/>
      </body>
    </html>
  );
}
