/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hSoa8Ip4Qom
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/


import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export function assistant() {
  return (
    <div className="flex flex-col h-screen">
      <header
        className="'bg-gray-20 dark:bg-gray-800 shadow-md fixed top-0 left-0 right-0 z-10 transition-transform duration-300 ease-in-out" 
      >
        <div className="container mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <h2 className="text-lg font-medium">Agent Ops Center</h2>
          </div>
          <div className="flex items-center space-x-2">
            <button className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300 ml-auto">
              <SettingsIcon className="h-5 w-5" />
            </button>
          </div>
        </div>
      </header>
      <div className="grid grid-cols-2 gap-6 mt-20">
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 flex flex-col">
          <div className="flex-1 overflow-y-auto space-y-4 pr-4">
            <div className="bg-white dark:bg-gray-900 rounded-lg p-4 shadow">
              <div className="flex items-start space-x-3">
                <Avatar>
                  <AvatarImage alt="AI Assistant" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>AI</AvatarFallback>
                </Avatar>
                <div>
                  <p className="text-sm">Hello, how can I assist you today?</p>
                  <div className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    <span>AI Assistant</span> • <span>Just now</span>
                  </div>
                </div>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-900 rounded-lg p-4 shadow">
              <div className="flex items-start space-x-3">
                <Avatar>
                  <AvatarImage alt="You" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>You</AvatarFallback>
                </Avatar>
                <div>
                  <p className="text-sm">Hi there, I have a few tasks I like to discuss.</p>
                  <div className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    <span>You</span> • <span>Just now</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="mt-4">
            <Input className="w-full" placeholder="Type your message..." />
          </div>
        </div>
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-6 flex flex-col">
          <div className="flex-1 overflow-y-auto space-y-4 pr-4">
            <div className="bg-white dark:bg-gray-900 rounded-lg p-4 shadow flex items-center">
              <div className="flex-1">
                <p className="text-sm">Task 1: Completed</p>
                <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Description of Task 1 and its output.</p>
              </div>
              <div className="ml-4">
                <CheckIcon className="h-5 w-5 text-green-500" />
              </div>
            </div>
            <div className="bg-white dark:bg-gray-900 rounded-lg p-4 shadow flex items-center">
              <div className="flex-1">
                <p className="text-sm">Task 2: In Progress</p>
                <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                  Description of Task 2 and its current status.
                </p>
              </div>
              <div className="ml-4">
                <LoaderIcon className="h-5 w-5 text-yellow-500 animate-spin" />
              </div>
            </div>
            <div className="bg-white dark:bg-gray-900 rounded-lg p-4 shadow flex items-center">
              <div className="flex-1">
                <p className="text-sm">Task 3: Pending</p>
                <p className="text-sm text-gray-500 dark:text-gray-400 mt-1">
                  Description of Task 3 and its current status.
                </p>
              </div>
              <div className="ml-4">
                <ClockIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
              </div>
            </div>
          </div>
        </div>
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg" />
        <div className="bg-gray-100 dark:bg-gray-800 rounded-lg" />
      </div>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}
interface IconProps extends React.SVGProps<SVGSVGElement> {}


function ClockIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function LoaderIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="6" />
      <line x1="12" x2="12" y1="18" y2="22" />
      <line x1="4.93" x2="7.76" y1="4.93" y2="7.76" />
      <line x1="16.24" x2="19.07" y1="16.24" y2="19.07" />
      <line x1="2" x2="6" y1="12" y2="12" />
      <line x1="18" x2="22" y1="12" y2="12" />
      <line x1="4.93" x2="7.76" y1="19.07" y2="16.24" />
      <line x1="16.24" x2="19.07" y1="7.76" y2="4.93" />
    </svg>
  )
}


function SettingsIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}
